import fs from "fs-extra";
import path from "node:path";
import { execa } from "execa";
import { copyAndBuildMcp, defaultNonSecretEnv, envExample, launcherScript, timestamp } from "../core/build.js";
import { ExtensionManifest } from "../core/manifest.js";
import { workspaceRoot } from "../core/paths.js";
import { setInstalled, removeInstalled } from "../core/state.js";

export async function buildClaudeDesktopExtension(manifest: ExtensionManifest): Promise<string> {
  const root = workspaceRoot();
  const extensionDir = path.join(root, "platforms", "claude-desktop", "extensions", manifest.id);
  await fs.remove(extensionDir);
  await copyAndBuildMcp(manifest, path.join(extensionDir, "server"));
  await fs.ensureDir(path.join(extensionDir, "scripts"));
  await fs.writeFile(path.join(extensionDir, "scripts", `start-${manifest.id}.mjs`), launcherScript());
  await fs.chmod(path.join(extensionDir, "scripts", `start-${manifest.id}.mjs`), 0o755);
  await fs.writeFile(path.join(extensionDir, ".env.example"), envExample(manifest));
  await fs.writeFile(path.join(extensionDir, ".mcpbignore"), mcpbIgnore());
  await fs.writeJson(path.join(extensionDir, "manifest.json"), desktopManifest(manifest), { spaces: 2 });
  await fs.writeFile(path.join(extensionDir, "README.md"), `# ${manifest.name}\n\nClaude Desktop MCPB extension generated by aix.\n`);

  const distDir = path.join(root, "dist", "claude-desktop");
  await fs.ensureDir(distDir);
  const output = path.join(distDir, `${manifest.id}.mcpb`);
  await execa("npx", ["--yes", "@anthropic-ai/mcpb", "validate", path.join(extensionDir, "manifest.json")], { cwd: root, stdio: "inherit" });
  await execa("npx", ["--yes", "@anthropic-ai/mcpb", "pack", extensionDir, output], { cwd: root, stdio: "inherit" });
  return output;
}

export async function buildClaudeConnector(manifest: ExtensionManifest): Promise<string> {
  const root = workspaceRoot();
  const connectorDir = path.join(root, "platforms", "claude-desktop", "connectors", manifest.id);
  await fs.remove(connectorDir);
  await fs.ensureDir(connectorDir);
  await fs.writeJson(path.join(connectorDir, "connector.json"), {
    id: manifest.id,
    name: manifest.name,
    version: manifest.version,
    description: manifest.description,
    type: "remote-mcp-template",
    mcp: {
      transport: "http",
      url: "https://example.com/mcp",
      tools: manifest.mcp.tools
    },
    auth: {
      type: "oauth-or-api-key",
      note: "Fill this template when exposing the MCP server as a remote Claude connector."
    }
  }, { spaces: 2 });
  await fs.writeFile(path.join(connectorDir, "README.md"), `# ${manifest.name} Connector\n\nTemplate for a Claude remote connector backed by the shared MCP server.\n`);
  return connectorDir;
}

export async function installClaudeDesktopExtension(manifest: ExtensionManifest): Promise<string> {
  const bundle = await buildClaudeDesktopExtension(manifest);
  await setInstalled(manifest.id, "claude-desktop", {
    version: manifest.version,
    installedPath: bundle,
    installedAt: new Date().toISOString()
  });
  return bundle;
}

export async function removeClaudeDesktopExtension(extensionId: string): Promise<void> {
  await fs.remove(path.join(workspaceRoot(), "dist", "claude-desktop", `${extensionId}.mcpb`));
  await removeInstalled(extensionId, "claude-desktop");
}


function desktopAuthor(manifest: ExtensionManifest) {
  return {
    name: manifest.metadata.platforms.claudeDesktop.author.name ?? manifest.metadata.publisher.name,
    email: manifest.metadata.platforms.claudeDesktop.author.email ?? manifest.metadata.publisher.email,
    url: manifest.metadata.platforms.claudeDesktop.author.url ?? manifest.metadata.publisher.url
  };
}

function desktopManifest(manifest: ExtensionManifest) {
  return {
    manifest_version: "0.2",
    name: manifest.id,
    version: `${manifest.version}+desktop.${timestamp()}`,
    description: manifest.description,
    author: desktopAuthor(manifest),
    server: {
      type: "node",
      entry_point: `scripts/start-${manifest.id}.mjs`,
      mcp_config: {
        command: "node",
        args: [`${"${__dirname}"}/scripts/start-${manifest.id}.mjs`],
        env: defaultNonSecretEnv(manifest)
      }
    },
    license: manifest.license ?? "MIT"
  };
}


function mcpbIgnore(): string {
  return [
    "server/src/**",
    "server/tests/**",
    "server/docs/**",
    "server/*.tsbuildinfo",
    "server/.env*",
    "server/.gitignore",
    "server/scripts/**",
    "server/tsconfig.json",
    "server/package-lock.json",
    "server/package.json",
    "**/*.map",
    "**/*.ts",
    "**/.DS_Store"
  ].join("\n") + "\n";
}
